### ISSUE TITLE
Enchanting too expensive.

### ISSUE THREAD

**Issue by K4N0** [wyldmods/ToolUtilities#10]
I have set the enchanting to be at 50L for the 3X3 but when i try and enchant it. 
It says too expensive. It still allows me to enchant it and takes away the proper amount, but some players might not realize this.

**Comment by tterrag1098** [comment]
The vanilla anvil has a hard limit of 40 levels, this is not the fault of the mod. If you want to change it my mod [EnderCore](http://minecraft.curseforge.com/projects/endercore) has a config to change this max level.

**Comment by K4N0** [comment]
Nice! Thank you. I did know about the hard limit, i just wasn't sure there was a way to change this.
