### ISSUE TITLE
Testing various mod weapons and tools

### ISSUE THREAD

**Issue by Fortist** [wyldmods/ToolUtilities#4]
First is Redstone Arse.
Gotta go ham on the first test, yo.

http://pastebin.com/PXnPdjSJ

We Metallhurgy now.

http://pastebin.com/tjWBHBsE

But every other set of weapons seem to work, even randomthing's and extra util's swords. And Gany'send swords which teleport stuff on kill.

Ill test with enchants at another time.
Ill test the tools later as well. Me thinks twilight forest's pick may have a problem, or maybe Gany's tools will mess up? Later testing~

**Comment by K4N0** [comment]
Anything you'd like to add to a mod showcase. I'll be getting one done this next weekend.
Also this mod is definetly going into the modpack Mojangsters from the technic launcher.
http://www.technicpack.net/modpack/mojangsters.583708

Visit our new youtube channel.
https://www.youtube.com/channel/UCVRDbrSypbA696FHcaiBhkg
